version: "2"
run:
  tests: true
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Allow cobra-style unused args
      - linters:
          - unused
        path: cmd/
        text: args is unused
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/yourname/rocker-project-template
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
